apiVersion: apps/v1
kind: ReplicaSet
netadata:
  name: nginx
  labels: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
    tier: frontend
  template:
    metadata:
      name: nginx
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
