---
  apiVersion: v1
  kind: Pod
  metadata:
    name: nginx
    labels:
      app: pod-example
  spec:
    containers:
    - name: web
      image: nginx:1.7.9
      ports:
      - containerPort: 80

      